owner: rabenherz112         # GitHub username
repo: uptime-monitor        # GitHub repository name

sites:                      # List of Endpoints to track
  - name: Ravenhub (Main Page)
    url: $URL_RH_MAIN
    assignees:
      - rabenherz112
  - name: Ravenhub URL Shortner (Frontend)
    url: $URL_RH_URL_RAVSHORT
    assignees:
      - rabenherz112
  - name: Ravenhub URL Shortner (Backend)
    url: $URL_RH_URL
    assignees:
      - rabenherz112
  - name: Ravenhub Builderman (Website)
    url: $URL_RH_BUILDER
    assignees:
      - rabenherz112
  - name: Ravenhub Dropbox
    url: $URL_RH_URL_DROPBOX
    assignees:
      - rabenherz112
  - name: Ravenhub ShareX
    url: $URL_RH_SHAREX
    assignees:
      - rabenherz112
  - name: VS-NETCUP-01 (Server)
    check: "tcp-ping"
    url: $URL_VS_NETCUP01
    port: 53
    assignees:
      - rabenherz112
  - name: VS-STRATO-01 (Server)
    check: "tcp-ping"
    url: $URL_VS_STRATO01
    port: 53
    assignees:
      - rabenherz112
  - name: VS-LIS-HETZNER01 (Server)
    check: "tcp-ping"
    url: $URL_VS_LIS_HETZNER01
    port: 53
    assignees:
      - lischetzke

status-website:
  cname: status.theravenhub.com
  favicon: https://media.discordapp.net/attachments/731166978806644827/887707966520840202/L2.png
  logoUrl: https://media.discordapp.net/attachments/731166978806644827/887707966520840202/L2.png
  name: Ravenhub Monitoring Service
  theme: night
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: URL Shortner
      href: https://utility.theravenhub.com/url/
    - title: Builderman
      href: https://builderman.theravenhub.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: "Ravenhub Systems"
  commitAuthorEmail: "uptime@theravenhub.com"

workflowSchedule:
  graphs: "0 */12 * * *"
  responseTime: "0 */12 * * *"
  staticSite: "*/30 * * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 */12 * * *"
  updates: "*/10 * * * *"
  uptime: "*/5 * * * *"
